language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: zhenlingcn
  password:
    secure: bN3u6BiR8f8aZTP3js5jK+usvHzG9ifesmH7r8YyveoMKIRqbf7UuJtyUNiEv4LFhr0n5qjZ+/Ap2yTmLTODBd6U/m0styTXb6C9yuZtWzY1InX5+eGDKWTqPcWT5iHVS91OYwNV5BJAt6VI6bfWzNaIf03Gtl68EfPXgOfoYTmwupM8aq0OVgL6UguWPeZ9H2hH6mafiD3rx2KybXqAKshzR/RladLnHAngyQPSvn5ssoyIsZHnLPqytHXRVMAcSWGwmuDY5UHqko2jSG5YUfUVRbapFrdmaBbywclA6/G/vD+tvC3uE64yhnigEizaBFdp6uRu+lCZe+vOl/N5qU28MA/6im4aePRfde1xO4OlQjdpXP1ZPrPZ/tFcR0ER9AOlOfxmWwJcD36TSP8znLPiriQzBIhFUoHKnWvahcdNNvYNHKPXgZhI5aBfO4IENUwA3atS5xifS3AMZ/Q1kJirMNrChxKjOQ9RJ9t4m3HGy71+N/pFmNAuioYFMOt49KOW+bvEalfALMaMdo/hJWO82dxEQC7rAxyqxUes50pRb6L+IgX9a+thk9nXzk1+hR/T1sxiFNkYjPVFSO+KkVQ5PqPtaPmjpFydn21zECJm5D4ciHqymCxy77OOAIkG8bnQr/9m3kq6BxvEdgcavveSxOsbXbDSPEjFWjkJpD8=
  on:
    tags: true
    repo: zhenlingcn/EvolutionaryForest
    python: 3.8
