language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: zhenlingcn
  password:
    secure: jb94MpSmTgmIEcLi2KQRuHWkVODowHKPOHBIi78eX8V7r3UfnaIVWiN+3r0g7mivYCzOaJOvpPu+ufO/lK3Fn4KUzpEkIeXWOzP86ARF+w3oeRHnSztAAAk8d9vKXu2ZXj4XlUlmFhCx1WY0E3sXPDBVNSw0FtRc7I2IQUBk6Prk62DdXbMNlrYuBQ5/cAk9iF1XvlPVjE8hTYz4vzcOdpbxml4KERhfii9ovW8J3C1dpbwADJIQJIf+jXnRu29knri3GL3SZGXZ3Rm14EgSpHnHmu0lhMq5UmboKITTVUA5OBmCxowH8bVPum00c6fcdQWbt3WnL5yHzpznjSOZ7cjwp1jWXGraOR4WNolaG4M8tXDgzAZ994DIdfZaQciRGgb0G11YfUSz2p+c94FF8S1Knq1C5lSOiWGJd5fBThsFj71LrhcKg8XvzXSa3RD6tn8Hne0fpAft6AjJ0jN9EXqeUWUBp9etIfevFLxMz7tGelx9QTAHNQUAz5YGNbQfXrcYPcZegG8Qo10BOrpj/7Tw6CpU5Htkt4EZr27/OgbuerS2t+h2F7Mn6N8G/fvWwtmcM9sJ2dXtiQThQvOvuH9y5EqX8laex/41Z7YMvZx2n80TnAk2SIRXHvdajiT/+aV/ZIBc3TpPPWMqgm4cr1x0zzqX6aERe9atGdwy7yI=
  on:
    tags: true
    repo: zhenlingcn/EvolutionaryForest
    python: 3.8
